---
description: Pipeline for Nessus vulnerability data.
processors:
  - json:
      field: message
      target_field: _tmp
      ignore_failure: true

  - rename:
      field: _tmp.nessus
      target_field: nessus
      ignore_missing: true

  - script:
      lang: painless
      description: Set @timestamp from scan_end epoch seconds.
      source: |
        def val = ctx.nessus?.scan_end;
        if (val == null) return;
        if (val instanceof Number) {
          ctx['@timestamp'] = Instant.ofEpochSecond(((Number) val).longValue()).toString();
        } else if (val instanceof String) {
          ctx['@timestamp'] = val;
        }
      ignore_failure: true

  - script:
      lang: painless
      description: Map severity, CVSS scores, CVE, references, and dates.
      source: |
        def sev = ctx.nessus?.severity;
        if (sev == null) return;

        Map ecs_labels = new HashMap();
        ecs_labels.put(0, 'LOW');
        ecs_labels.put(1, 'LOW');
        ecs_labels.put(2, 'MEDIUM');
        ecs_labels.put(3, 'HIGH');
        ecs_labels.put(4, 'CRITICAL');

        if (ctx.nessus == null) ctx.nessus = new HashMap();
        ctx.nessus.put('severity_ecs', ecs_labels.getOrDefault(sev, 'LOW'));

        if (ctx.vulnerability == null) ctx.vulnerability = new HashMap();

        // CVSS score: prefer cvss3, fallback to cvss2, then approximate
        if (ctx.vulnerability.score == null) ctx.vulnerability.put('score', new HashMap());
        def cvss3 = ctx.nessus?.cvss3_base_score;
        def cvss2 = ctx.nessus?.cvss_base_score;
        if (cvss3 != null && cvss3 instanceof String && cvss3.length() > 0) {
          ctx.vulnerability.score.put('base', Double.parseDouble(cvss3));
          ctx.vulnerability.score.put('version', '3.0');
        } else if (cvss2 != null && cvss2 instanceof String && cvss2.length() > 0) {
          ctx.vulnerability.score.put('base', Double.parseDouble(cvss2));
          ctx.vulnerability.score.put('version', '2.0');
        } else {
          Map fallback = new HashMap();
          fallback.put(0, 0.0); fallback.put(1, 3.0);
          fallback.put(2, 5.5); fallback.put(3, 7.5); fallback.put(4, 9.5);
          ctx.vulnerability.score.put('base', fallback.getOrDefault(sev, 0.0));
          ctx.vulnerability.score.put('version', '3.0');
        }

        // CVSS vector
        def v3vec = ctx.nessus?.cvss3_vector;
        if (v3vec != null && v3vec instanceof String && v3vec.length() > 0) {
          ctx.vulnerability.score.put('environmental_score_modifier', v3vec);
        }

        // CVE list → vulnerability.id and vulnerability.enumeration
        def cves = ctx.nessus?.cve;
        if (cves != null && cves instanceof List && cves.size() > 0) {
          ctx.vulnerability.put('id', cves[0]);
          ctx.vulnerability.put('enumeration', 'CVE');
          ctx.vulnerability.put('reference', cves);
        } else {
          ctx.vulnerability.put('id', 'nessus-plugin-' + String.valueOf(ctx.nessus.plugin_id));
          ctx.vulnerability.put('enumeration', 'NESSUS');
          ctx.vulnerability.put('reference', []);
        }

        // Description
        def desc = ctx.nessus?.description;
        if (desc != null && desc instanceof String && desc.length() > 0) {
          ctx.vulnerability.put('description', desc);
        } else {
          def pname = ctx.nessus?.plugin_name;
          ctx.vulnerability.put('description', pname != null ? pname : '');
        }

        // Published date from plugin_pub_date (format: "YYYY/MM/DD")
        def pubDate = ctx.nessus?.plugin_pub_date;
        if (pubDate != null && pubDate instanceof String && pubDate.length() >= 10) {
          def normalized = pubDate.replace('/', '-') + 'T00:00:00.000Z';
          ctx.vulnerability.put('published_date', normalized);
        }

        // see_also → vulnerability.reference (URLs)
        def seeAlso = ctx.nessus?.see_also;
        if (seeAlso != null && seeAlso instanceof List && seeAlso.size() > 0) {
          def refs = ctx.vulnerability.reference != null ? ctx.vulnerability.reference : [];
          for (def url : seeAlso) {
            if (!refs.contains(url)) {
              refs.add(url);
            }
          }
          ctx.vulnerability.put('reference', refs);
        }
      ignore_failure: true

  # ── event.id — required by Findings page grouping queries ──
  - set:
      field: event.id
      value: "{{nessus.scan_id}}-{{nessus.host_ip}}-{{nessus.plugin_id}}"
      ignore_empty_value: true

  - set:
      field: ecs.version
      value: "8.11.0"
  - set:
      field: event.kind
      value: state
  - set:
      field: event.category
      value: ["vulnerability"]
  - set:
      field: event.type
      value: ["info"]
  - set:
      field: event.module
      value: nessus
  - set:
      field: event.dataset
      value: nessus.vulnerability
  - set:
      field: event.severity
      value: "{{nessus.severity}}"
      ignore_empty_value: true
  - convert:
      field: event.severity
      type: integer
      ignore_missing: true
      ignore_failure: true

  - set:
      field: host.ip
      value: ["{{nessus.host_ip}}"]
      ignore_empty_value: true
  - set:
      field: host.name
      value: "{{nessus.hostname}}"
      ignore_empty_value: true
  - set:
      field: host.hostname
      value: "{{nessus.hostname}}"
      ignore_empty_value: true
  - set:
      field: host.domain
      value: "{{nessus.host_fqdn}}"
      ignore_empty_value: true
  - set:
      field: host.os.full
      value: "{{nessus.host_os}}"
      ignore_empty_value: true

  - set:
      field: vulnerability.title
      value: "{{nessus.plugin_name}}"
      ignore_empty_value: true
  - set:
      field: vulnerability.category
      value: ["{{nessus.plugin_family}}"]
      ignore_empty_value: true
  - set:
      field: vulnerability.severity
      value: "{{nessus.severity_ecs}}"
      ignore_empty_value: true
  - set:
      field: vulnerability.classification
      value: CVSS
  - set:
      field: vulnerability.scanner.vendor
      value: Tenable
  - set:
      field: vulnerability.scanner.name
      value: Nessus
  - set:
      field: vulnerability.report_id
      value: "{{nessus.scan_uuid}}"
      ignore_empty_value: true

  - set:
      field: resource.id
      value: "{{nessus.host_ip}}"
      ignore_empty_value: true
  - set:
      field: resource.name
      value: "{{nessus.hostname}}"
      ignore_empty_value: true
  - set:
      field: resource.type
      value: host

  - set:
      field: observer.vendor
      value: Tenable

  - append:
      field: related.ip
      value: "{{nessus.host_ip}}"
      allow_duplicates: false
      ignore_failure: true
  - append:
      field: related.hosts
      value: "{{nessus.hostname}}"
      allow_duplicates: false
      ignore_failure: true
  - append:
      field: related.hosts
      value: "{{nessus.host_fqdn}}"
      allow_duplicates: false
      ignore_failure: true

  - remove:
      field:
        - _tmp
        - message
      ignore_missing: true

on_failure:
  - set:
      field: event.kind
      value: pipeline_error
  - append:
      field: error.message
      value: "{{ _ingest.on_failure_message }}"
